title: "Les Affaires à Marcel"
description: "Mes affaires de moto à vendre"
url: "https://moto.marcelgerber.ch"  # or your custom domain
baseurl: ""  # leave blank if using a custom domain

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: single

collections:
  pages:
    output: true

  gear:
    output: true
    permalink: /gear/:path/

exclude:
  - gems/

